import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/app/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
  title: "Whispr",
  description: "Generated by Hamza Anwar Mohiuddin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider >
      <body>
        {children}
        <Toaster />
      </body>
      </AuthProvider>

    </html>
  );
}
